import { readdirSync, existsSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";
import { defineConfig } from "vitest/config";

const ROOT = dirname(fileURLToPath(import.meta.url));

/**
 * Resolve `@massingviewer/*` to package **source**, not built `dist/`.
 *
 * This is not a convenience. Without it the test run resolves through each package's `exports` field, which
 * points at `./dist/index.js` — so:
 *
 *  - **CI fails and local passes.** CI runs `npm ci` then `vitest` with no build step, so `dist/` does not
 *    exist and cross-package imports fail with "Failed to resolve entry for package". Locally it worked only
 *    because a previous `tsc --build` had left `dist/` lying around. That is the worst shape of CI failure:
 *    invisible on the machine where the code was written.
 *  - **Tests can pass against stale output.** Editing a source file and re-running would test the previous
 *    build. A green suite proving nothing about the code in front of you is worse than a red one.
 *
 * Generated by scanning `packages/` rather than hand-listed, so a new package is wired up by existing rather
 * than by remembering to edit this file.
 */
function workspaceAliases(): Record<string, string> {
  const aliases: Record<string, string> = {};
  for (const name of readdirSync(join(ROOT, "packages"))) {
    const entry = join(ROOT, "packages", name, "src", "index.ts");
    if (existsSync(entry)) aliases[`@massingviewer/${name}`] = entry;
  }
  return aliases;
}

// One root Vitest run across every workspace package. Deliberately not per-package projects: the
// import-graph and provenance gates are repo-wide assertions that need to see every file at once, and
// splitting the run would let a package pass in isolation while violating a layering rule.
export default defineConfig({
  resolve: { alias: workspaceAliases() },
  test: {
    include: ["packages/**/*.test.ts", "apps/**/*.test.ts", "fixtures/**/*.test.ts", "scripts/**/*.test.mjs"],
    exclude: ["**/node_modules/**", "**/dist/**"],
    environment: "node",
    // Only the packages that touch the DOM opt into happy-dom, via `// @vitest-environment happy-dom`
    // at the top of the file. Defaulting to node keeps the pure-math suite fast, which is what makes
    // it the suite people actually run before pushing.
    coverage: {
      provider: "v8",
      reporter: ["text-summary", "json-summary", "lcov"],
      include: ["packages/*/src/**/*.ts"],
      exclude: ["**/*.test.ts", "**/index.ts", "**/*.d.ts"],
      thresholds: {
        // Per-package floors. geometry-math and kernel-api are the load-bearing pure layers; the
        // conformance suite depends on them being right, so they carry the highest floor.
        "packages/geometry-math/src/**": { statements: 90, branches: 85, functions: 90, lines: 90 },
        "packages/kernel-api/src/**": { statements: 90, branches: 80, functions: 90, lines: 90 },
        "packages/core/src/**": { statements: 80, branches: 75, functions: 80, lines: 80 },
      },
    },
  },
});
