/**
 * The service worker, emitted as source text by a pure function.
 *
 * ## One worker, two jobs, and why they could not be two workers
 *
 * A page can have exactly one controlling service worker per scope. massing hit this and resolved it by choosing:
 * `VITE_PAGES` swaps the Workbox PWA worker out and `coi-serviceworker` in, because the two fight. That trade is
 * real — offline caching *or* `SharedArrayBuffer`, not both — and it is the wrong one for a tool whose headline
 * claim is that it works offline.
 *
 * So both behaviours live in one worker: precache-and-serve, plus optional response-header rewriting for
 * cross-origin isolation. They compose because they act at different points of the same `fetch` handler — the
 * cache decides *what* the response is, the isolation pass decides *what headers it carries*. Two workers cannot
 * compose at all.
 *
 * ## Hand-written rather than Workbox
 *
 * Workbox generates a worker whose `fetch` handler is its own, which is precisely the part that must also do the
 * header rewrite — so combining them means either patching generated output or running Workbox's handler and then
 * failing to reach the response it already returned. Writing the ~90 lines directly makes the interaction
 * explicit and removes a large transitive dependency tree from a package whose SBOM is a shipped artifact. The
 * repository hand-writes its PDF and IFC serialisers for the same reason.
 *
 * ## Emitted as a string, and therefore testable
 *
 * A service worker is a separate script with a different global type (`ServiceWorkerGlobalScope`), so it cannot be
 * imported by the app it serves. Generating it as text keeps the precache manifest, the cache name and the
 * isolation switch as *inputs* — so `swSource()` is a pure function of its options and the tests assert on what
 * it emits rather than on a checked-in file nobody diffs.
 */

export interface SwOptions {
  /**
   * Cache name. Must change when the precached content changes, or the old bundle is served forever.
   *
   * The plugin derives it from a hash of the manifest for exactly that reason — a hand-maintained version string
   * is a cache invalidation bug waiting for someone to forget it.
   */
  readonly cacheName: string;
  /** URLs to precache at install. Relative to the worker's scope. */
  readonly precache: readonly string[];
  /**
   * Rewrite navigation responses with COOP/COEP so the page becomes cross-origin isolated.
   *
   * **Off by default, and that is a decision rather than a default.** COEP `require-corp` blocks every
   * cross-origin subresource that does not opt in with CORP/CORS — so turning this on when nothing needs
   * `SharedArrayBuffer` does not buy latent readiness, it breaks images, fonts and iframes at a distance and the
   * breakage looks like a network fault. Nothing in this repository needs SAB today: there is no
   * `@thatopen/fragments`, no `web-ifc`, and no `Atomics` use. Turn it on with the thing that needs it.
   */
  readonly crossOriginIsolation?: boolean;
  /** The document served for a navigation that misses the cache. Usually `index.html`. */
  readonly shell?: string;
}

/**
 * A short digest of the precache manifest, used as the cache name.
 *
 * FNV-1a rather than SHA-256, and deliberately not `node:crypto`: this module is imported by browser code, and
 * pulling `node:crypto` in got it externalised by Vite with a warning. Nothing here is security-sensitive — the
 * digest only has to *change* when the manifest changes, so a new deploy is never served the old cache. The PDF
 * writer's `/ID` uses the same hash for the same reason.
 */
export function manifestDigest(precache: readonly string[]): string {
  let hash = 0x81_1c_9d_c5;
  for (const char of precache.join("\n")) {
    hash ^= char.codePointAt(0)!;
    // `Math.imul` keeps the multiply in 32 bits. A plain `*` overflows into a float and silently stops mixing the
    // high bits, which collapses the output range to almost nothing.
    hash = Math.imul(hash, 0x01_00_01_93) >>> 0;
  }
  return hash.toString(16).padStart(8, "0");
}

/** JSON, but safe to embed in a script: `</script` inside a string would end the script element early. */
function embed(value: unknown): string {
  return JSON.stringify(value).replaceAll("<", "\\u003c");
}

/** Generate the worker's source. */
export function swSource(options: SwOptions): string {
  const { cacheName, precache, crossOriginIsolation = false, shell = "index.html" } = options;

  return `// Generated by @massing/pwa. Do not edit — change the plugin options instead.
const CACHE = ${embed(cacheName)};
const PRECACHE = ${embed([...precache])};
const SHELL = ${embed(shell)};
const ISOLATE = ${crossOriginIsolation ? "true" : "false"};
/**
 * How long a navigation waits for the network before the cached shell wins.
 *
 * Two seconds is chosen against the *user*, not the network: below it a fast connection still serves fresh, above
 * it the app is visibly slower to open than the cache could have made it. The cost is that a deploy made while
 * the network is this slow is picked up one navigation later than it would have been — which is the right trade,
 * because the assets are content-hashed and the stale shell references the same ones.
 */
const NAV_TIMEOUT_MS = 2000;

self.addEventListener("install", (event) => {
  event.waitUntil(
    (async () => {
      const cache = await caches.open(CACHE);
      // Added one at a time rather than with addAll, because addAll rejects as a unit: one 404 in the manifest
      // discards every other entry and the app has no offline copy at all. A missing asset should cost that
      // asset. The failures are reported, so this is not silence — it is a partial install that says so.
      const failed = [];
      await Promise.all(
        PRECACHE.map(async (url) => {
          try {
            // \`reload\` so install never populates the cache from the HTTP cache. Priming a fresh service worker
            // with a stale copy of the previous deploy is the bug this whole mechanism exists to avoid.
            await cache.add(new Request(url, { cache: "reload" }));
          } catch {
            failed.push(url);
          }
        }),
      );
      if (failed.length > 0) console.warn("[pwa] precache missed", failed);
    })(),
  );
  // Activate without waiting for existing tabs to close. Safe here because \`activate\` deletes only caches
  // belonging to other versions, and each version's assets are content-hashed, so an old tab keeps working.
  self.skipWaiting();
});

self.addEventListener("activate", (event) => {
  event.waitUntil(
    (async () => {
      for (const name of await caches.keys()) {
        if (name !== CACHE) await caches.delete(name);
      }
      await self.clients.claim();
    })(),
  );
});

/**
 * Add the two headers that make a document cross-origin isolated.
 *
 * A new Response is constructed rather than the original mutated: \`response.headers\` is immutable on a response
 * that came from the network, so setting a header on it throws and the navigation fails outright.
 */
function isolate(response) {
  if (!ISOLATE || !response || response.type === "opaque" || response.status === 0) return response;
  const headers = new Headers(response.headers);
  headers.set("Cross-Origin-Opener-Policy", "same-origin");
  headers.set("Cross-Origin-Embedder-Policy", "require-corp");
  return new Response(response.body, { status: response.status, statusText: response.statusText, headers });
}

self.addEventListener("fetch", (event) => {
  const request = event.request;
  if (request.method !== "GET") return;

  const url = new URL(request.url);
  // Same-origin only. Rewriting a third party's response headers is not ours to do, and caching one would break
  // the "no third-party origins" property the Pages workflow asserts on the built output.
  if (url.origin !== self.location.origin) return;

  event.respondWith(
    (async () => {
      const cache = await caches.open(CACHE);

      // A navigation resolves to the shell. Network first so a deploy is picked up promptly, cache second so the
      // app opens with no network at all — which is the offline claim, and it has to survive a reload rather than
      // only a session.
      if (request.mode === "navigate") {
        try {
          /**
           * Bounded, and the bound is the point.
           *
           * \`fetch\` only rejects when the network stack gives up, which on a dead-but-connected link — a captive
           * portal, hotel wifi, a train entering a tunnel — is tens of seconds rather than immediate. Until then
           * this handler holds \`respondWith\` open and the user sees nothing, despite a complete, content-hashed
           * copy of the app sitting in the cache. "Offline" as a browser state is not the same as "no network as
           * far as this request is concerned", and only the second one is what the user is living in.
           */
          const fresh = await Promise.race([
            fetch(request),
            new Promise((_, reject) => {
              setTimeout(() => reject(new Error("shell fetch exceeded NAV_TIMEOUT_MS")), NAV_TIMEOUT_MS);
            }),
          ]);
          if (fresh.ok) {
            await cache.put(SHELL, fresh.clone());
            return isolate(fresh);
          }
        } catch {
          /* offline, or slower than the cache is worth waiting for — fall through to the cache */
        }
        const cached = (await cache.match(request)) ?? (await cache.match(SHELL));
        if (cached) return isolate(cached);
        return isolate(await fetch(request));
      }

      // Assets are content-hashed by the bundler, so a cache hit is definitionally current and going to the
      // network would be pure latency.
      const cached = await cache.match(request);
      if (cached) return isolate(cached);

      const fresh = await fetch(request);
      // Only 200s are stored. Caching a 206 corrupts a later full read, and caching a redirect or an error
      // makes the failure permanent for as long as the cache lives.
      if (fresh.status === 200 && fresh.type === "basic") await cache.put(request, fresh.clone());
      return isolate(fresh);
    })(),
  );
});
`;
}

/**
 * The registration snippet for the page.
 *
 * Separate from the worker because it runs in the document, and it is generated for the same reason: the one-time
 * reload below is easy to get wrong and must not be re-derived per app.
 */
export function registrationSource(options: { readonly swUrl: string; readonly crossOriginIsolation?: boolean }): string {
  const { swUrl, crossOriginIsolation = false } = options;
  return `// Generated by @massing/pwa.
if ("serviceWorker" in navigator) {
  navigator.serviceWorker.register(${embed(swUrl)}).then((registration) => {
    ${
      crossOriginIsolation
        ? `// One reload, once. The worker cannot add headers to the navigation that installed it — that response
    // was already on the wire — so the first load of a new install is never isolated. Reloading once makes it
    // so. Guarded on \`controller\`, because reloading whenever isolation is absent would loop forever in a
    // browser that withholds SharedArrayBuffer for some other reason.
    if (!window.crossOriginIsolated && navigator.serviceWorker.controller === null && registration.active !== null) {
      window.location.reload();
    }`
        : `// No reload: without isolation there is nothing that needs to be in place before the document loads,
    // and the cache serves the *next* visit either way.`
    }
  }).catch((error) => {
    // Registration failure must not be fatal. It costs the offline cache; the app still works online, and a
    // thrown error here would take down a page that is otherwise fine.
    console.warn("[pwa] service worker registration failed", error);
  });
}
`;
}
